remapping post survey answers to match datatypes
techmatters/serverless pull request #362
Opened 2022-11-28 19:17 UTC by janorivera

Reviewer
@Humairaa127 
## Description

I'm updating this because I think that the type of answers don't match the current data type for the Twilio attribute.

2022-11-29 09:29 UTC, Humairaa127 commented
The flex insights config is already using this attribute, so that needs to be adjusted if there are any left:
     {
        "name": "memberOfAnEthnic",
        "insights": ["conversations", "conversation_measure_4"],
        "type": "mixed-checkbox"
      }

2022-11-29 09:30 UTC, Humairaa127 requested changes
The flex insights config is already using this one attribute, so that needs to be adjusted if there are any left:
{
"name": "memberOfAnEthnic",
"insights": ["conversations", "conversation_measure_4"],
"type": "mixed-checkbox"
}

2022-11-29 11:05 UTC, janorivera commented
@Humairaa127 yes! I'm preparing a PR in flex-plugins with all the proper adjustments. I have a call with them today to have a final discussion about the things that they want to store and I'll raise the PR so you can review it.

2022-12-01 07:00 UTC, Humairaa127 approved these changes

2022-12-01 11:26 UTC, merged